name: cs6400-app
services:
  db:
    hostname: db
    image: postgres:17.0
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@test.local"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['local']"
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    ports:
      - "8082:80"
    depends_on:
      - "db"
  backend:
    hostname: backend
    build:
      context: ./backend/
    ports:
      - "8081:5000"
    depends_on:
      - "db"
  frontend:
    hostname: frontend
    build:
      context: ./frontend/
    ports:
      - "8080:80"
    depends_on:
      - "backend"

volumes:
  db-data:
  pgadmin-data:

configs:
  pgpass:
    content: |
      db:5432:*:dealership:dealership
      db:5432:*:postgres:postgres
  servers.json:
    content: |
      {"Servers": {"1": {
        "Name": "dealership@db",
        "Group": "Servers",
        "Host": "db",
        "Port": 5432,
        "MaintenanceDB": "dealership",
        "Username": "dealership",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }, "2": {
        "Name": "postgres@db",
        "Group": "Servers",
        "Host": "db",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "postgres",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}